# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d89588a10536da9817627e9a8429db3aecc449d63c9e12a84f0e2ee7bbcd23669c7e4dc7c820cef2d70295ef6623d1c79f8f07946d570ecb7cdc0de8f78df766

test:
  secret_key_base: 20083f983d088ab02ddc302132101e1b1b31a0e175042df8bab30c99721ead15079ba7844d4bdea42d57b2f27b5015afc214e63871e85d0cfb8ad215cbb5b9a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
